version: "3.9"
services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: user_meetly
      POSTGRES_PASSWORD: Tu67LOP152F
      POSTGRES_DB: MeetlyDB
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: